# shop-sock-dev-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop-sock-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/exam-rncp/shop-sock.git
    targetRevision: dev
    path: .
    helm:
      valueFiles:
        - values-test.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true